import type { Notification } from '../../types/notification';

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    title: 'Transaction Successful',
    message: 'Your airtime purchase of ₦500 to 08012345678 was successful.',
    type: 'transaction',
    priority: 'medium',
    isRead: false,
    isActive: true,
    formattedDate: '29 Jan 2025, 10:30 AM',
    formattedReadDate: null,
  },
  {
    id: 2,
    title: 'Wallet Credited',
    message: 'Your wallet has been credited with ₦50,000.00 from bank transfer.',
    type: 'success',
    priority: 'high',
    isRead: true,
    isActive: true,
    formattedDate: '28 Jan 2025, 02:15 PM',
    formattedReadDate: '28 Jan 2025, 02:20 PM',
  },
  {
    id: 3,
    title: 'Promotion: 10% Bonus',
    message: 'Get 10% bonus on your next data purchase. Use code DATA10 at checkout.',
    type: 'promotion',
    priority: 'low',
    isRead: false,
    isActive: true,
    formattedDate: '27 Jan 2025, 09:00 AM',
    formattedReadDate: null,
  },
  {
    id: 4,
    title: 'System Maintenance',
    message: 'Scheduled maintenance on Jan 30, 2025 between 2:00 AM - 4:00 AM. Services may be briefly unavailable.',
    type: 'system',
    priority: 'medium',
    isRead: true,
    isActive: true,
    formattedDate: '26 Jan 2025, 06:00 PM',
    formattedReadDate: '26 Jan 2025, 06:05 PM',
  },
  {
    id: 5,
    title: 'Transaction Failed',
    message: 'Your electricity payment of ₦5,000 could not be completed. Please try again or contact support.',
    type: 'error',
    priority: 'urgent',
    isRead: false,
    isActive: true,
    formattedDate: '25 Jan 2025, 11:45 AM',
    formattedReadDate: null,
    metadata: { reference: 'TXN-2025-001236' },
  },
];
